---
  host:
    description: "Hostname or IP address of firewall."
    type: "string"
    required: true
  port:
    description: "TCP port number for the firewall connection."
    type: "integer"
    default: 443
  api_username:
    description: "Authentication user-id for the firewall api."
    type: "string"
    required: false
  api_password:
    description: "The password of the specified user."
    type: "string"
    secret: true
    required: false
  api_key:
    description: "The api key for this user."
    type: "string"
    secret: true
    required: false